get:
  summary: Retrieve a project
  operationId: retrieve_project_by_id
  description: Retrieve a project by ID
  tags:
    - Projects
  security:
    - jwt: []
  parameters:
    - $ref: ../parameters/path/project_id.yaml
  responses:
    200:
      description: project retrieved successfully
      content:
        application/json:
          schema:
            $ref: ../schemas/project.yaml
    400:
      $ref: ../responses/bad_request.yaml
    401:
      $ref: ../responses/unauthorized.yaml
    403:
      $ref: ../responses/forbidden.yaml
    500:
      $ref: ../responses/internal_server_error.yaml

put:
  summary: Update a project
  operationId: update_project_by_id
  description: Update a project by ID
  tags:
    - Projects
  security:
    - jwt: []
  parameters:
    - $ref: ../parameters/path/project_id.yaml
  requestBody:
    description: project object that needs to be updated
    required: true
    content:
      application/json:
        schema:
          $ref: ../schemas/update_project.yaml
  responses:
    200:
      description: project updated successfully
      content:
        application/json:
          schema:
            $ref: ../schemas/project.yaml
    400:
      $ref: ../responses/bad_request.yaml
    401:
      $ref: ../responses/unauthorized.yaml
    403:
      $ref: ../responses/forbidden.yaml
    404:
      $ref: ../responses/not_found.yaml
    409:
      $ref: ../responses/conflict.yaml
    422:
      $ref: ../responses/unprocessable_entity.yaml
    500:
      $ref: ../responses/internal_server_error.yaml


delete:
  summary: Delete a project
  operationId: delete_project_by_id
  description: Delete a project by ID
  tags:
    - Projects
  security:
    - jwt: []
  parameters:
    - $ref: ../parameters/path/project_id.yaml
  responses:
    204:
      description: project deleted successfully
    400:
      $ref: ../responses/bad_request.yaml
    401:
      $ref: ../responses/unauthorized.yaml
    403:
      $ref: ../responses/forbidden.yaml
    404:
      $ref: ../responses/not_found.yaml
    409:
      $ref: ../responses/conflict.yaml
    500:
      $ref: ../responses/internal_server_error.yaml
