openapi: 3.1.1
info:
  version: 1.0.0
  title: The Projects API description
  description: The Projects API description of the Mairie360 Projects API
  contact:
    name: Clément Antoine XAVIER
    url: https://github.com/marie360/projects-api-description
    email: clement-antoine.xavier@epitech.eu
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://projects.api.development.mairie360.fr
    description: Development server
tags:
  - name: Projects
    description: Projects operations
security: 
  - jwt: []
paths:
  /projects:
    $ref: ./resources/projects.yaml
  /projects/{project_id}:
    $ref: ./resources/project.yaml
components:
  parameters:
    $ref: ./parameters/_index.yaml
  schemas:
    $ref: ./schemas/_index.yaml
  responses:
    $ref: ./responses/_index.yaml
  securitySchemes:
    $ref: ./security_schemes/_index.yaml
